module.exports = {
    collectCoverage: true,
    moduleFileExtensions: [
        "js",
        "jsx",
        "json",
    ],
    globals: {
        window: true,
    },
    collectCoverageFrom: ["**/*.jsx", "**/*.js"],
    moduleDirectories: ["node_modules", ".", "__mocks__", "__tests__", "components", "helpers", "pages", "redux"],
    testMatch: [
        "**/*.(test|spec).(js)",
    ],
    setupFilesAfterEnv: ["<rootDir>/__tests__/setup.js"],
    setupFiles: ["jest-localstorage-mock"],
    coverageReporters: [
        "json",
        "lcov",
    ],
    coveragePathIgnorePatterns: [
        "/node_modules/",
        "setup.js",
        "jest.config.js",
        "next.config.js",
        "setup.js",
        "/utils/",
        "/static/",
        "/locales/",
        "/coverage/",
        "/authConfig/",
        "/api/",
        "/__mocks__/",
        "/__tests__/",
        "components/HOC/helpers",
        "pages/_app.js",
        "pages/_document.js",
        "redux/store.js",
        "redux/reducers/index.js",
        "redux/sagas/index.js",
        "ecosystem.config.js",
        "pages/index.js",
        "helpers/asyncActions.js",
        "server.js",
        "index.js",
    ],
    moduleNameMapper: {
        "^.+\\.(css|scss)$": "identity-obj-proxy",
    },
};
